### ISSUE TITLE
StreamClient: Howto

### ISSUE THREAD

**Issue by kurt-s** [api-ai/apiai-javascript-client#40]
I'm trying to let users ask questions through their microphones, convert that to text and send it to api.ai. I've implemented the StreamClient example code from the README content and it seems to at least init the stream client since my browser asks me whether I want to allow access to the mic for that web portal. I can also see that the "onInit" function is being triggered. 

My initial design is simple: user hits a button on the portal and starts asking the question - once he/she stops talking (1-2 seconds of silence) I'd assume that the speech recorder stops recording and either provides the result in text form (a string that I can use to call the api.ai /query method) or automatically pushes the recoreded audio to api.ai and provides the results from the server as JSON.

How would I achieve that?
Thanks
Kurt

**Comment by Gugic** [comment]
Hi. I am not currently sure that end-of-speech detection is currently working well. But you definitely should be able to do following:
1) streamClient.init()
2) streamClient.startListening() (can be triggered by button click)
3) streamClient.stopListening() (ideally should be triggered automatically by end-of-speech detection, but can be called manually, by timeout or button)

After stopListening streamClient will send items to speechrec and then to api.ai and will give you result inside onResults callback (that you should assign manually)

But unfortunately this things will be deprecated soon, so currently I can only advice you to use browser built-in speechrec (https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) which is better then api.ai's or some separate speechrec service.

I hope we will implement some of this approaches in SDK.

**Comment by kurt-s** [comment]
Thank you for the clear feedback on the current state and plans. In that case, I will look for alternative speech recognition solutions (like the one from Mozilla you referenced).
Kurt
