### ISSUE TITLE
Disable microphone request

### ISSUE THREAD

**Issue by daxiang28** [api-ai/apiai-javascript-client#44]
Hi, 
I was wondering if there was a way to disable the microphone request. I'm using the client for text and don't want to have users confirm mic access every time they load the page. 

Thanks,
Steve

**Comment by Gugic** [comment]
Hi,
How exactly you are using SDK?

**Comment by daxiang28** [comment]
@Gugic I'm essentially using it like the [demo](https://github.com/api-ai/apiai-javascript-client/tree/master/demo/simple) and couldn't figure out an option or config for disabling microphone access. I just need the text response parts to it.

**Comment by Gugic** [comment]
Then use https://github.com/api-ai/apiai-javascript-client/blob/master/target/ApiAi.streamless.min.js this version of library instead of full.

**Comment by daxiang28** [comment]
@Gugic Sorry I didn't see your response till now. Is there any documentation for how you use the streamless version? I can't seem to instantiate it correctly.

**Comment by daxiang28** [comment]
Ok, this turned out to be pretty stupid, but the documentation is vague on this. My assumption that the eventRequest opened up a listener to a message stream. I was mixing up terminology with 'listener' and assuming it was listening for responses and not voice. The simple text example on the readme works just fine for basic text messaging purposes. 
https://github.com/api-ai/apiai-javascript-client#textrequest

**Comment by SiddAjmera** [comment]
Can someone please help me out with an EventRequest Example. I'm trying to find one out but I'm not getting one.

All I want is to make the user press a button, get the audio and send the audio to my DialogFlow Agent using DialogFlow's JavaScript SDK

Can someone please help!

Thanks
